apiVersion: v1
kind: Service
metadata:
  name: nodejs-demo-service
spec:
  type: NodePort
  selector:
    app: nodejs-demo-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
